#include <stdio.h>
#include <stdlib.h>

#include "registers.h"
#include "debug.h"

#include "cb.h"

const struct instruction extendedInstructions[256] = {
	{ "RLC B", 0, NULL },
	{ "RLC C", 0, NULL },
	{ "RLC D", 0, NULL },
	{ "RLC E", 0, NULL },
	{ "RLC H", 0, NULL },
	{ "RLC L", 0, NULL },
	{ "RLC (HL)", 0, NULL },
	{ "RLC A", 0, NULL },
	{ "RRC B", 0, NULL },
	{ "RRC C", 0, NULL },
	{ "RRC D", 0, NULL },
	{ "RRC E", 0, NULL },
	{ "RRC H", 0, NULL },
	{ "RRC L", 0, NULL },
	{ "RRC (HL)", 0, NULL },
	{ "RRC A", 0, NULL },
	{ "RL B", 0, NULL },
	{ "RL C", 0, NULL },
	{ "RL D", 0, NULL }, 
	{ "RL E", 0, NULL },
	{ "RL H", 0, NULL },
	{ "RL L", 0, NULL },
	{ "RL (HL)", 0, NULL },
	{ "RL A", 0, NULL },
	{ "RR B", 0, NULL },
	{ "RR C", 0, NULL },
	{ "RR D", 0, NULL },
	{ "RR E", 0, NULL },
	{ "RR H", 0, NULL },
	{ "RR L", 0, NULL },
	{ "RR (HL)", 0, NULL },
	{ "RR A", 0, NULL },
	{ "SLA B", 0, NULL },
	{ "SLA C", 0, NULL },
	{ "SLA D", 0, NULL },
	{ "SLA E", 0, NULL },
	{ "SLA H", 0, NULL },
	{ "SLA L", 0, NULL },
	{ "SLA (HL)", 0, NULL },
	{ "SLA A", 0, NULL }, 
	{ "SRA B", 0, NULL },
	{ "SRA C", 0, NULL },
	{ "SRA D", 0, NULL },
	{ "SRA E", 0, NULL },
	{ "SRA H", 0, NULL },
	{ "SRA L", 0, NULL },
	{ "SRA (HL)", 0, NULL },
	{ "SRA A", 0, NULL },
	{ "SWAP B", 0, NULL },
	{ "SWAP C", 0, NULL },
	{ "SWAP D", 0, NULL },
	{ "SWAP E", 0, NULL },
	{ "SWAP H", 0, NULL },
	{ "SWAP L", 0, NULL },
	{ "SWAP (HL)", 0, NULL },
	{ "SWAP A", 0, NULL }, 
	{ "SRL B", 0, NULL },
	{ "SRL C", 0, NULL },
	{ "SRL D", 0, NULL },
	{ "SRL E", 0, NULL },
	{ "SRL H", 0, NULL },
	{ "SRL L", 0, NULL },
	{ "SRL (HL)", 0, NULL },
	{ "SRL A", 0, NULL },
	{ "BIT 0, B", 0, NULL },
	{ "BIT 0, C", 0, NULL },
	{ "BIT 0, D", 0, NULL },
	{ "BIT 0, E", 0, NULL },
	{ "BIT 0, H", 0, NULL },
	{ "BIT 0, L", 0, NULL }, 
	{ "BIT 0, (HL)", 0, NULL },
	{ "BIT 0, A", 0, NULL }, 
	{ "BIT 1, B", 0, NULL },
	{ "BIT 1, C", 0, NULL },
	{ "BIT 1, D", 0, NULL },
	{ "BIT 1, E", 0, NULL },
	{ "BIT 1, H", 0, NULL },
	{ "BIT 1, L", 0, NULL },
	{ "BIT 1, (HL)", 0, NULL }, 
	{ "BIT 1, A", 0, NULL },
	{ "BIT 2, B", 0, NULL },
	{ "BIT 2, C", 0, NULL },
	{ "BIT 2, D", 0, NULL },
	{ "BIT 2, E", 0, NULL },
	{ "BIT 2, H", 0, NULL },
	{ "BIT 2, L", 0, NULL },
	{ "BIT 2, (HL)", 0, NULL },
	{ "BIT 2, A", 0, NULL },
	{ "BIT 3, B", 0, NULL },
	{ "BIT 3, C", 0, NULL },
	{ "BIT 3, D", 0, NULL },
	{ "BIT 3, E", 0, NULL },
	{ "BIT 3, H", 0, NULL },
	{ "BIT 3, L", 0, NULL }, 
	{ "BIT 3, (HL)", 0, NULL },
	{ "BIT 3, A", 0, NULL }, 
	{ "BIT 4, B", 0, NULL },
	{ "BIT 4, C", 0, NULL },
	{ "BIT 4, D", 0, NULL },
	{ "BIT 4, E", 0, NULL },
	{ "BIT 4, H", 0, NULL },
	{ "BIT 4, L", 0, NULL }, 
	{ "BIT 4, (HL)", 0, NULL },
	{ "BIT 4, A", 0, NULL },
	{ "BIT 5, B", 0, NULL },
	{ "BIT 5, C", 0, NULL }, 
	{ "BIT 5, D", 0, NULL },
	{ "BIT 5, E", 0, NULL },
	{ "BIT 6, H", 0, NULL },
	{ "BIT 6, L", 0, NULL },
	{ "BIT 5, (HL)", 0, NULL },
	{ "BIT 5, A", 0, NULL },
	{ "BIT 6, B", 0, NULL },
	{ "BIT 6, C", 0, NULL },
	{ "BIT 6, D", 0, NULL },
	{ "BIT 6, E", 0, NULL },
	{ "BIT 6, H", 0, NULL },
	{ "BIT 6, L", 0, NULL }, 
	{ "BIT 6, (HL)", 0, NULL },
	{ "BIT 6, A", 0, NULL },
	{ "BIT 7, B", 0, NULL },
	{ "BIT 7, C", 0, NULL },
	{ "BIT 7, D", 0, NULL },
	{ "BIT 7, E", 0, NULL },
	{ "BIT 7, H", 0, NULL },
	{ "BIT 7, L", 0, NULL },
	{ "BIT 7, (HL)", 0, NULL }, 
	{ "BIT 7, A", 0, NULL },
	{ "RES 0, B", 0, NULL },
	{ "RES 0, C", 0, NULL },
	{ "RES 0, D", 0, NULL },
	{ "RES 0, E", 0, NULL },
	{ "RES 0, H", 0, NULL },
	{ "RES 0, L", 0, NULL },
	{ "RES 0, (HL)", 0, NULL },
	{ "RES 0, A", 0, NULL }, 
	{ "RES 1, B", 0, NULL },
	{ "RES 1, C", 0, NULL },
	{ "RES 1, D", 0, NULL },
	{ "RES 1, E", 0, NULL },
	{ "RES 1, H", 0, NULL },
	{ "RES 1, L", 0, NULL },
	{ "RES 1, (HL)", 0, NULL },
	{ "RES 1, A", 0, NULL },
	{ "RES 2, B", 0, NULL },
	{ "RES 2, C", 0, NULL },
	{ "RES 2, D", 0, NULL },
	{ "RES 2, E", 0, NULL },
	{ "RES 2, H", 0, NULL },
	{ "RES 2, L", 0, NULL },
	{ "RES 2, (HL)", 0, NULL },
	{ "RES 2, A", 0, NULL },
	{ "RES 3, B", 0, NULL },
	{ "RES 3, C", 0, NULL },
	{ "RES 3, D", 0, NULL },
	{ "RES 3, E", 0, NULL },
	{ "RES 3, H", 0, NULL },
	{ "RES 3, L", 0, NULL },
	{ "RES 3, (HL)", 0, NULL },
	{ "RES 3, A", 0, NULL },
	{ "RES 4, B", 0, NULL },
	{ "RES 4, C", 0, NULL },
	{ "RES 4, D", 0, NULL },
	{ "RES 4, E", 0, NULL },
	{ "RES 4, H", 0, NULL },
	{ "RES 4, L", 0, NULL },
	{ "RES 4, (HL)", 0, NULL },
	{ "RES 4, A", 0, NULL },
	{ "RES 5, B", 0, NULL },
	{ "RES 5, C", 0, NULL },
	{ "RES 5, D", 0, NULL },
	{ "RES 5, E", 0, NULL },
	{ "RES 5, H", 0, NULL },
	{ "RES 5, L", 0, NULL },
	{ "RES 5, (HL)", 0, NULL },
	{ "RES 5, A", 0, NULL },
	{ "RES 6, B", 0, NULL },
	{ "RES 6, C", 0, NULL },
	{ "RES 6, D", 0, NULL },
	{ "RES 6, E", 0, NULL },
	{ "RES 6, H", 0, NULL },
	{ "RES 6, L", 0, NULL },
	{ "RES 6, (HL)", 0, NULL },
	{ "RES 6, A", 0, NULL },
	{ "RES 7, B", 0, NULL },
	{ "RES 7, C", 0, NULL },
	{ "RES 7, D", 0, NULL },
	{ "RES 7, E", 0, NULL },
	{ "RES 7, H", 0, NULL },
	{ "RES 7, L", 0, NULL }, 
	{ "RES 7, (HL)", 0, NULL }, 
	{ "RES 7, A", 0, NULL },
	{ "SET 0, B", 0, NULL },
	{ "SET 0, C", 0, NULL },
	{ "SET 0, D", 0, NULL },
	{ "SET 0, E", 0, NULL },
	{ "SET 0, H", 0, NULL },
	{ "SET 0, L", 0, NULL },
	{ "SET 0, (HL)", 0, NULL },
	{ "SET 0, A", 0, NULL },
	{ "SET 1, B", 0, NULL },
	{ "SET 1, C", 0, NULL },
	{ "SET 1, D", 0, NULL },
	{ "SET 1, E", 0, NULL },
	{ "SET 1, H", 0, NULL },
	{ "SET 1, L", 0, NULL },
	{ "SET 1, (HL)", 0, NULL },
	{ "SET 1, A", 0, NULL },
	{ "SET 2, B", 0, NULL },
	{ "SET 2, C", 0, NULL },
	{ "SET 2, D", 0, NULL },
	{ "SET 2, E", 0, NULL },
	{ "SET 2, H", 0, NULL },
	{ "SET 2, L", 0, NULL },
	{ "SET 2, (HL)", 0, NULL },
	{ "SET 2, A", 0, NULL },
	{ "SET 3, B", 0, NULL },
	{ "SET 3, C", 0, NULL },
	{ "SET 3, D", 0, NULL },
	{ "SET 3, E", 0, NULL },
	{ "SET 3, H", 0, NULL },
	{ "SET 3, L", 0, NULL },
	{ "SET 3, (HL)", 0, NULL },
	{ "SET 3, A", 0, NULL },
	{ "SET 4, B", 0, NULL },
	{ "SET 4, C", 0, NULL },
	{ "SET 4, D", 0, NULL },
	{ "SET 4, E", 0, NULL },
	{ "SET 4, H", 0, NULL },
	{ "SET 4, L", 0, NULL },
	{ "SET 4, (HL)", 0, NULL },
	{ "SET 4, A", 0, NULL },
	{ "SET 5, B", 0, NULL },
	{ "SET 5, C", 0, NULL },
	{ "SET 5, D", 0, NULL },
	{ "SET 5, E", 0, NULL },
	{ "SET 5, H", 0, NULL },
	{ "SET 5, L", 0, NULL },
	{ "SET 5, (HL)", 0, NULL },
	{ "SET 5, A", 0, NULL },
	{ "SET 6, B", 0, NULL },
	{ "SET 6, C", 0, NULL },
	{ "SET 6, D", 0, NULL },
	{ "SET 6, E", 0, NULL },
	{ "SET 6, H", 0, NULL },
	{ "SET 6, L", 0, NULL },
	{ "SET 6, (HL)", 0, NULL },
	{ "SET 6, A", 0, NULL },
	{ "SET 7, B", 0, NULL },
	{ "SET 7, C", 0, NULL },
	{ "SET 7, D", 0, NULL },
	{ "SET 7, E", 0, NULL },
	{ "SET 7, H", 0, NULL },
	{ "SET 7, L", 0, NULL },
	{ "SET 7, (HL)", 0, NULL },
	{ "SET 7, A", 0, NULL },
};

void cb_n(unsigned char instruction) {
	if(!extendedInstructions[instruction].execute) {
		printf("Unimplemented extended instruction 0x%02x (%s)!\n",  instruction, extendedInstructions[instruction].disassembly);
		
		registers.pc -= 2;
		printRegisters();
		exit(1);
	}
}
