#include <stdio.h>
#include <stdlib.h>

#include "registers.h"
#include "debug.h"

#include "cb.h"

const struct extendedInstruction extendedInstructions[256] = {
	{ "RLC B", NULL },
	{ "RLC C", NULL },
	{ "RLC D", NULL },
	{ "RLC E", NULL },
	{ "RLC H", NULL },
	{ "RLC L", NULL },
	{ "RLC (HL)", NULL },
	{ "RLC A", NULL },
	{ "RRC B", NULL },
	{ "RRC C", NULL },
	{ "RRC D", NULL },
	{ "RRC E", NULL },
	{ "RRC H", NULL },
	{ "RRC L", NULL },
	{ "RRC (HL)", NULL },
	{ "RRC A", NULL },
	{ "RL B", NULL },
	{ "RL C", NULL },
	{ "RL D", NULL }, 
	{ "RL E", NULL },
	{ "RL H", NULL },
	{ "RL L", NULL },
	{ "RL (HL)", NULL },
	{ "RL A", NULL },
	{ "RR B", NULL },
	{ "RR C", NULL },
	{ "RR D", NULL },
	{ "RR E", NULL },
	{ "RR H", NULL },
	{ "RR L", NULL },
	{ "RR (HL)", NULL },
	{ "RR A", NULL },
	{ "SLA B", NULL },
	{ "SLA C", NULL },
	{ "SLA D", NULL },
	{ "SLA E", NULL },
	{ "SLA H", NULL },
	{ "SLA L", NULL },
	{ "SLA (HL)", NULL },
	{ "SLA A", NULL }, 
	{ "SRA B", NULL },
	{ "SRA C", NULL },
	{ "SRA D", NULL },
	{ "SRA E", NULL },
	{ "SRA H", NULL },
	{ "SRA L", NULL },
	{ "SRA (HL)", NULL },
	{ "SRA A", NULL },
	{ "SWAP B", NULL },
	{ "SWAP C", NULL },
	{ "SWAP D", NULL },
	{ "SWAP E", NULL },
	{ "SWAP H", NULL },
	{ "SWAP L", NULL },
	{ "SWAP (HL)", NULL },
	{ "SWAP A", NULL }, 
	{ "SRL B", NULL },
	{ "SRL C", NULL },
	{ "SRL D", NULL },
	{ "SRL E", NULL },
	{ "SRL H", NULL },
	{ "SRL L", NULL },
	{ "SRL (HL)", NULL },
	{ "SRL A", NULL },
	{ "BIT 0, B", NULL },
	{ "BIT 0, C", NULL },
	{ "BIT 0, D", NULL },
	{ "BIT 0, E", NULL },
	{ "BIT 0, H", NULL },
	{ "BIT 0, L", NULL }, 
	{ "BIT 0, (HL)", NULL },
	{ "BIT 0, A", NULL }, 
	{ "BIT 1, B", NULL },
	{ "BIT 1, C", NULL },
	{ "BIT 1, D", NULL },
	{ "BIT 1, E", NULL },
	{ "BIT 1, H", NULL },
	{ "BIT 1, L", NULL },
	{ "BIT 1, (HL)", NULL }, 
	{ "BIT 1, A", NULL },
	{ "BIT 2, B", NULL },
	{ "BIT 2, C", NULL },
	{ "BIT 2, D", NULL },
	{ "BIT 2, E", NULL },
	{ "BIT 2, H", NULL },
	{ "BIT 2, L", NULL },
	{ "BIT 2, (HL)", NULL },
	{ "BIT 2, A", NULL },
	{ "BIT 3, B", NULL },
	{ "BIT 3, C", NULL },
	{ "BIT 3, D", NULL },
	{ "BIT 3, E", NULL },
	{ "BIT 3, H", NULL },
	{ "BIT 3, L", NULL }, 
	{ "BIT 3, (HL)", NULL },
	{ "BIT 3, A", NULL }, 
	{ "BIT 4, B", NULL },
	{ "BIT 4, C", NULL },
	{ "BIT 4, D", NULL },
	{ "BIT 4, E", NULL },
	{ "BIT 4, H", NULL },
	{ "BIT 4, L", NULL }, 
	{ "BIT 4, (HL)", NULL },
	{ "BIT 4, A", NULL },
	{ "BIT 5, B", NULL },
	{ "BIT 5, C", NULL }, 
	{ "BIT 5, D", NULL },
	{ "BIT 5, E", NULL },
	{ "BIT 6, H", NULL },
	{ "BIT 6, L", NULL },
	{ "BIT 5, (HL)", NULL },
	{ "BIT 5, A", NULL },
	{ "BIT 6, B", NULL },
	{ "BIT 6, C", NULL },
	{ "BIT 6, D", NULL },
	{ "BIT 6, E", NULL },
	{ "BIT 6, H", NULL },
	{ "BIT 6, L", NULL }, 
	{ "BIT 6, (HL)", NULL },
	{ "BIT 6, A", NULL },
	{ "BIT 7, B", NULL },
	{ "BIT 7, C", NULL },
	{ "BIT 7, D", NULL },
	{ "BIT 7, E", NULL },
	{ "BIT 7, H", NULL },
	{ "BIT 7, L", NULL },
	{ "BIT 7, (HL)", NULL }, 
	{ "BIT 7, A", NULL },
	{ "RES 0, B", NULL },
	{ "RES 0, C", NULL },
	{ "RES 0, D", NULL },
	{ "RES 0, E", NULL },
	{ "RES 0, H", NULL },
	{ "RES 0, L", NULL },
	{ "RES 0, (HL)", NULL },
	{ "RES 0, A", NULL }, 
	{ "RES 1, B", NULL },
	{ "RES 1, C", NULL },
	{ "RES 1, D", NULL },
	{ "RES 1, E", NULL },
	{ "RES 1, H", NULL },
	{ "RES 1, L", NULL },
	{ "RES 1, (HL)", NULL },
	{ "RES 1, A", NULL },
	{ "RES 2, B", NULL },
	{ "RES 2, C", NULL },
	{ "RES 2, D", NULL },
	{ "RES 2, E", NULL },
	{ "RES 2, H", NULL },
	{ "RES 2, L", NULL },
	{ "RES 2, (HL)", NULL },
	{ "RES 2, A", NULL },
	{ "RES 3, B", NULL },
	{ "RES 3, C", NULL },
	{ "RES 3, D", NULL },
	{ "RES 3, E", NULL },
	{ "RES 3, H", NULL },
	{ "RES 3, L", NULL },
	{ "RES 3, (HL)", NULL },
	{ "RES 3, A", NULL },
	{ "RES 4, B", NULL },
	{ "RES 4, C", NULL },
	{ "RES 4, D", NULL },
	{ "RES 4, E", NULL },
	{ "RES 4, H", NULL },
	{ "RES 4, L", NULL },
	{ "RES 4, (HL)", NULL },
	{ "RES 4, A", NULL },
	{ "RES 5, B", NULL },
	{ "RES 5, C", NULL },
	{ "RES 5, D", NULL },
	{ "RES 5, E", NULL },
	{ "RES 5, H", NULL },
	{ "RES 5, L", NULL },
	{ "RES 5, (HL)", NULL },
	{ "RES 5, A", NULL },
	{ "RES 6, B", NULL },
	{ "RES 6, C", NULL },
	{ "RES 6, D", NULL },
	{ "RES 6, E", NULL },
	{ "RES 6, H", NULL },
	{ "RES 6, L", NULL },
	{ "RES 6, (HL)", NULL },
	{ "RES 6, A", NULL },
	{ "RES 7, B", NULL },
	{ "RES 7, C", NULL },
	{ "RES 7, D", NULL },
	{ "RES 7, E", NULL },
	{ "RES 7, H", NULL },
	{ "RES 7, L", NULL }, 
	{ "RES 7, (HL)", NULL }, 
	{ "RES 7, A", NULL },
	{ "SET 0, B", NULL },
	{ "SET 0, C", NULL },
	{ "SET 0, D", NULL },
	{ "SET 0, E", NULL },
	{ "SET 0, H", NULL },
	{ "SET 0, L", NULL },
	{ "SET 0, (HL)", NULL },
	{ "SET 0, A", NULL },
	{ "SET 1, B", NULL },
	{ "SET 1, C", NULL },
	{ "SET 1, D", NULL },
	{ "SET 1, E", NULL },
	{ "SET 1, H", NULL },
	{ "SET 1, L", NULL },
	{ "SET 1, (HL)", NULL },
	{ "SET 1, A", NULL },
	{ "SET 2, B", NULL },
	{ "SET 2, C", NULL },
	{ "SET 2, D", NULL },
	{ "SET 2, E", NULL },
	{ "SET 2, H", NULL },
	{ "SET 2, L", NULL },
	{ "SET 2, (HL)", NULL },
	{ "SET 2, A", NULL },
	{ "SET 3, B", NULL },
	{ "SET 3, C", NULL },
	{ "SET 3, D", NULL },
	{ "SET 3, E", NULL },
	{ "SET 3, H", NULL },
	{ "SET 3, L", NULL },
	{ "SET 3, (HL)", NULL },
	{ "SET 3, A", NULL },
	{ "SET 4, B", NULL },
	{ "SET 4, C", NULL },
	{ "SET 4, D", NULL },
	{ "SET 4, E", NULL },
	{ "SET 4, H", NULL },
	{ "SET 4, L", NULL },
	{ "SET 4, (HL)", NULL },
	{ "SET 4, A", NULL },
	{ "SET 5, B", NULL },
	{ "SET 5, C", NULL },
	{ "SET 5, D", NULL },
	{ "SET 5, E", NULL },
	{ "SET 5, H", NULL },
	{ "SET 5, L", NULL },
	{ "SET 5, (HL)", NULL },
	{ "SET 5, A", NULL },
	{ "SET 6, B", NULL },
	{ "SET 6, C", NULL },
	{ "SET 6, D", NULL },
	{ "SET 6, E", NULL },
	{ "SET 6, H", NULL },
	{ "SET 6, L", NULL },
	{ "SET 6, (HL)", NULL },
	{ "SET 6, A", NULL },
	{ "SET 7, B", NULL },
	{ "SET 7, C", NULL },
	{ "SET 7, D", NULL },
	{ "SET 7, E", NULL },
	{ "SET 7, H", NULL },
	{ "SET 7, L", NULL },
	{ "SET 7, (HL)", NULL },
	{ "SET 7, A", NULL },
};

void cb_n(unsigned char instruction) {
	if(!extendedInstructions[instruction].execute) {
		printf("Unimplemented extended instruction 0x%02x (%s)!\n",  instruction, extendedInstructions[instruction].disassembly);
		
		registers.pc -= 2;
		printRegisters();
		exit(1);
	}
}
